---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-psql-pvc
  namespace: zabbix
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-psql
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-psql
  template:
    metadata:
      labels:
        app: zabbix-psql
    spec:
      containers:
        - name: zabbix-psql
          image: postgres:15.6
          env:
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-secrets
                key: POSTGRES_PASSWORD
          volumeMounts:
            - name: zabbix-psql-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: zabbix-psql-data
          persistentVolumeClaim:
            claimName: zabbix-psql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-psql
  namespace: zabbix
spec:
  selector:
    app: zabbix-psql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

