apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:alpine-7.0.4
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
        env:
          - name: DB_SERVER_HOST
            value: zabbix-psql
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-secrets
                key: POSTGRES_PASSWORD
          - name: ZBX_STARTVMWARECOLLECTORS
            value: "1"
        

---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  selector:
    app: zabbix-server
  ports:
    - protocol: TCP
      port: 10051
      targetPort: 10051
