apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: jenkins
  name: jenkins
spec:
  containers:
  - image: jenkins/jenkins:lts-jdk11
    name: jenkins
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeName: str-dckr-lnx-02
status: {}
