
database:
  url: jdbc:postgresql://postgres:5432/bitbucket
  driver: org.postgresql.Driver
  credentials:
    secretName: bitbucket
    usernameSecretKey: POSTGRES_USER
    passwordSecretKey: POSTGRES_PASSWORD

# Volume configuration
volumes:
  localHome:
    persistentVolumeClaim:
      create: true
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
    mountPath: "/var/atlassian/application-data/bitbucket"
  sharedHome:
    customVolume:
      persistentVolumeClaim:
        claimName: bitbucket-sharedhome-pvc
    mountPath: "/var/atlassian/application-data/shared-home"
    subPath:


# Ingress configuration
#
# To make the Atlassian product available from outside the K8s cluster an Ingress
# Controller should be pre-provisioned. With this in place the configuration below
# can be used to configure an appropriate Ingress Resource.
# https://atlassian.github.io/data-center-helm-charts/userguide/CONFIGURATION/#ingress
#
ingress:
  create: true
  className: "nginx"
  nginx: true
  maxBodySize: 250m
  host: bitbucket.str.local
  path: /
  https: true
  tlsSecretName: str-local-cert


atlassianAnalyticsAndSupport:
  analytics:
    enabled: false
  helmValues:
    enabled: false