apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flowise-pvc
  namespace: flowise
  labels:
    app: flowise
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi