apiVersion: v1
kind: Service
metadata:
  name: xsoar
  namespace: test
spec:
  clusterIP: None
  ports:
    - protocol: TCP
      port: 443
      targetPort: 6443
      name: 'http'
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: xsoar-1
  namespace: test
  labels:
    kubernetes.io/service-name: xsoar
addressType: IPv4
ports:
  - name: 'http'
    appProtocol: https
    protocol: TCP
    port: 6443
endpoints:
  - addresses:
      - "10.3.0.95"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xsoar
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  rules:
  - host: xsoar.str.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: xsoar
            port:
              number: 443

