apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-data-pvc
  namespace: getoutline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  namespace: getoutline
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
