---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodered-pv-claim
  namespace: nodered
spec:
  storageClassName: longhorn
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi