apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docling-pvc
  namespace: docling
  labels:
    app: docling
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi