---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-local
  namespace: pg-benchmark
  labels:
    app: pg-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-local
  template:
    metadata:
      labels:
        app: postgres-local
    spec:
      containers:
        - name: postgres-local
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: pg-benchmark
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-local-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-local-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-local
  namespace: pg-benchmark
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres-local
